Setup workflows component library
DiamondLightSource/workflows pull request #121
Opened 2024-08-13 12:05 UTC by iamvigneshwars

2024-08-13 13:26 UTC, garryod requested changes

2024-08-13 13:26 UTC, garryod commented on UI/.devcontainer/Dockerfile
Could we just reference this upstream container in our `devcontainer.json`?

2024-08-13 13:26 UTC, garryod commented on UI/.devcontainer/docker-compose.yaml
Do we need to be using `docker-compose` here if it's just one service?

2024-08-13 13:26 UTC, garryod commented on UI/workflows-components/.gitignore
> +
This middle block is missing a comment

2024-08-13 13:26 UTC, garryod commented on UI/workflows-components/vite.config.ts
Can we drop the vite stuff from the component library?

2024-08-13 13:26 UTC, garryod commented on UI/workflows-components/package.json
> +    "eslint-plugin-react": "^7.35.0",
Can this be in `devDependencies`?

2024-08-14 16:24 UTC, garryod reviewed
Looks pretty good to me, but have tagged @abigailalexander as someone who knows this stuff

2024-08-14 16:24 UTC, garryod commented on .gitignore
> +node_modules
Should this be at the repo root or alongside the `package.json`?

2024-08-14 16:24 UTC, garryod commented on UI/workflows-lib/.gitignore
I think a lot of these want to be at the workspace level

2024-08-14 16:24 UTC, garryod commented on UI/workflows-lib/.gitignore
> +*.sw?
Can probably remove these

2024-08-15 08:40 UTC, abigailalexander commented
I think I might be missing something, but what is being built into a component library here? I can see references to `lib/main.ts` that doesn't seem to exist, nor any other `.ts` or `.tsx` files here. Is this PR just for setting up the config needed to build the future component library?

2024-08-15 09:22 UTC, iamvigneshwars commented
This PR is just a setup to the component library. The actual components will be added in separate PR's. @abigailalexander

2024-08-15 09:44 UTC, abigailalexander commented
Makes sense, thanks for clarifying! Looks good to me @iamvigneshwars

2024-08-15 09:45 UTC, abigailalexander submitted a review, later dismissed

2024-08-15 09:51 UTC, garryod approved these changes
LGTM

2024-08-15 09:52 UTC, garryod requested changes
This is such a nit pick, but can we rename the `UI` directory to `frontend`?

2024-08-15 09:59 UTC, garryod approved these changes

2024-08-15 10:08 UTC, merged