Add TasksFlow component
DiamondLightSource/workflows pull request #140
Opened 2024-08-27 11:07 UTC by iamvigneshwars

This PR adds a react component that takes a list of workflow tasks and create a Directed Acyclic Graph. Tests checks if the component uses the props and functions properly and renders without crashing, also includes tests for the custom functions used by the component.

2024-08-27 13:57 UTC, garryod requested changes
Got a few small things, but looking good
@abigailalexander would you mind taking a quick look?

2024-08-27 13:57 UTC, garryod commented on frontend/workflows-lib/lib/components/workflow/CustomNode.tsx
Might be worth naming this something task-y

2024-08-27 13:57 UTC, garryod commented on frontend/workflows-lib/lib/uilts/TasksFlowUtils.ts
> +  const g = new dagre.graphlib.Graph();
Can we rename `g` to `graph`

2024-08-27 13:57 UTC, garryod commented on frontend/workflows-lib/lib/uilts/TasksFlowUtils.ts
Could we move these methods to a file close to the workflow component?

2024-08-27 13:57 UTC, garryod commented on frontend/workflows-lib/stories/mockData/MockTasks.ts
Can we just dump this data in the story?

2024-08-28 08:58 UTC, garryod approved these changes
LGTM

2024-08-28 08:58 UTC, garryod requested changes
Any chance you could refactor the commits before merging? Mainly just to get rid of the last commit

2024-08-28 10:05 UTC, abigailalexander approved these changes
LGTM as well

2024-08-28 12:16 UTC, garryod approved these changes
LGTM

2024-08-28 12:53 UTC, merged