add pod securityContext clusterpolicy
DiamondLightSource/workflows pull request #27
Opened 2024-06-17 15:37 UTC by iamvigneshwars

2024-06-17 15:44 UTC, garryod requested changes

2024-06-17 15:44 UTC, garryod commented on charts/workflows/templates/pod-securitycontext-clusterpolicy.yaml
> +              runAsGroup: "{{ `{{values.data.gid | parse_json(@).to_number(@)}}` }}"
I think we also want to set the `runAsUser` to a value set in the `values.yaml`. We may also want to reject any pods with `allowPrivilegeEscalation` set to `true`

2024-06-17 15:44 UTC, garryod commented on charts/workflows/templates/pod-securitycontext-clusterpolicy.yaml
Do we need to set `spec.containers[].securityContext` too? Or is it covered by `spec.securityContext`?

2024-06-18 10:15 UTC, iamvigneshwars commented on charts/workflows/templates/pod-securitycontext-clusterpolicy.yaml
`spec.securityContext` covers it

2024-06-19 12:36 UTC, garryod requested changes

2024-06-19 12:36 UTC, garryod commented on charts/workflows/test-policy/pod-securitycontext/chainsaw-test.yaml
> +              runAsGroup: 1234
We also want to test the `runAsUser` is set appropriately and that setting `allowPrivilegeEscalation` results in a rejection

2024-06-19 14:01 UTC, garryod approved these changes

2024-06-19 14:01 UTC, merged