feat: Release please setup to automate releases
DiamondLightSource/workflows pull request #308
Opened 2024-11-29 12:34 UTC by iamvigneshwars

2024-11-29 14:26 UTC, garryod requested changes
A few thoughts:
- How do we want to handle the helm linting which at present requires us to bump the chart version with each change - presumably this should only now be bumped by release-please?
- This will still publish containers for every tag, which we don't want
- Is there a a reason we separate the docs? And what if the `mkdocs.yaml` is updated?
- How do we ensure that commits are conventional? As non-conventional ones will break our usage of release-please

2024-12-03 10:13 UTC, garryod commented on .github/workflows/_graph_proxy_container.yaml
> +          load: ${{ !(github.event_name == 'release' && startsWith(github.event.release.tag_name, 'graph-proxy@')) }}
Does this ever actually get called with a `release` event?

2024-12-04 16:11 UTC, garryod requested changes

2025-02-12 10:18 UTC, garryod requested changes

2025-02-12 10:18 UTC, garryod commented on release-please-config.json
> +    },
We probably don't need to release the helm charts as our ArgoCD instance points to `main`

2025-02-12 10:18 UTC, garryod commented on release-please-config.json
> +    },
We should update the `appVersion` in the corresponding charts `Chart.yaml` when we release a new container, this can be [done with extra-files](https://github.com/googleapis/release-please/blob/main/docs/customizing.md#updating-arbitrary-yaml-files)

2025-02-12 12:55 UTC, daurer commented on release-please-config.json
> +    },
removed all charts and also docs from automated releasing

2025-02-12 12:55 UTC, daurer commented on release-please-config.json
> +    },
done

2025-02-13 21:30 UTC, daurer commented
Have tested in a fork that 

- [x] PRs are created as expected including bump in appVersion of Chart.yaml
- [x] After merging the PR,  tags are created, e.g. <service>@v0.1.0
- [x] Also, containers are created and pushed with expected tags, e.g. ghcr.io/.../<service>:0.1.0

Things to improve in the future

- `node-workspace` and `cargo-workspace` to also create releases when dependencies are bumped in `/frontend` or `backend`

2025-02-14 10:03 UTC, garryod requested changes

2025-02-14 10:03 UTC, garryod commented on .github/workflows/_release_please.yaml
> +      - uses: googleapis/release-please-action@v4
Can we use a fully qualified version here?
```suggestion
      - uses: googleapis/release-please-action@v4.1.3
```

2025-02-14 10:03 UTC, garryod commented on release-please-config.json
It would probably be good to include a `bootstrap-sha` in here, just to mark where we're beginning release-please. Can always manually create releases if we want to publish something that hasn't been updated since

2025-02-14 10:03 UTC, garryod commented on release-please-config.json
> +  ],
What do these `extra-files` do in this context?

2025-02-14 12:13 UTC, daurer commented on release-please-config.json
done

2025-02-14 12:13 UTC, daurer commented on release-please-config.json
> +  ],
this was hangover from releasing docs

2025-02-14 13:06 UTC, garryod approved these changes
LGTM

2025-02-14 14:25 UTC, daurer approved these changes

2025-02-14 14:39 UTC, garryod approved these changes

2025-02-14 14:49 UTC, merged