Add graph proxy resolver function tests
DiamondLightSource/workflows pull request #323
Opened 2024-12-09 16:12 UTC by yousefmoazzam

This adds tests of the various queries, before the reorganisation of the code is done as mentioned in https://github.com/DiamondLightSource/workflows/pull/288#discussion_r1853857325

2024-12-16 11:26 UTC, yousefmoazzam commented
@iamvigneshwars This is a first attempt at testing the workflow resolver functions, would be interesting to hear if you have any thoughts on this

2024-12-16 15:58 UTC, iamvigneshwars commented
Is there any reason for not using the well maintained `mockito` crate 🤔

2024-12-16 16:26 UTC, yousefmoazzam commented
No reason at all, the first hits I got when searching something like "http mock rust" were `httpmock` and `wiremock`, so I just went with `httpmock` because it looked simple enough to use.

I can see `mockito` indeed has more stars than either, I'll try it out and see how it compares; cheers for pointing out `mockito`!

2025-01-06 12:10 UTC, garryod requested changes

2025-01-06 12:10 UTC, garryod commented on .github/workflows/_graph_proxy_code.yaml
> +          --release
Why do we need `--release` here?

2025-01-06 12:10 UTC, garryod commented on graph-proxy/src/graphql/workflows.rs
> +        );
Is there a better way to build this? Should we be using a GraphQL client for this?

2025-01-06 12:10 UTC, garryod commented on graph-proxy/src/graphql/workflows.rs
> +            .finish();
Can inline the `token` here as it's not used anywhere else

```suggestion
        let argo_server_url = Url::parse(&server.base_url()).unwrap();
        let schema = root_schema_builder()
            .data(ArgoServerUrl(argo_server_url))
            .data(None::<Authorization<Bearer>>)
            .finish();
```

2025-01-07 09:53 UTC, yousefmoazzam commented on graph-proxy/src/graphql/workflows.rs
> +        assert_eq!(resp.data, expected_data);
Thanks for the suggestion, that would make building the expected response much more readable, will do

2025-01-07 10:22 UTC, yousefmoazzam commented on .github/workflows/_graph_proxy_code.yaml
> +          --release
I found that running certain tests that make graphql queries with `cargo test` (no  `--release`) suffers the same issue as when running the graph-proxy with `cargo run serve` (no  `--release`): tokio reports a stack overflow when handling a query, and the test fails as a consequence.

I'll take another look at that stack overflow issue; revisiting the github issue I looked at before which mentioned the same issue, it looks like it was resolved early in December https://github.com/async-graphql/async-graphql/issues/1506

2025-01-07 10:26 UTC, yousefmoazzam commented on graph-proxy/src/graphql/workflows.rs
> +        );
Yeah you're probably right, this way is a bit fiddly, with the need to escape the curly braces - I'll try out using a proper client instead.

2025-01-07 10:29 UTC, yousefmoazzam commented on graph-proxy/src/graphql/workflows.rs
> +            .finish();
Ah good point, will make that change in all the tests

2025-01-07 14:26 UTC, yousefmoazzam commented on graph-proxy/src/graphql/workflows.rs
> +        );
Eh, after looking into some graphql clients, it feels like some are a bit overkill:
- [`graphql-client`](https://github.com/graphql-rust/graphql-client?tab=readme-ov-file#getting-started) is the most popular rust client, but it needs a file with the schema, and a file with the desired query, which feels unnecessary for the purposes of testing using small queries
- similar thing for [`cynic`](https://cynic-rs.dev/quickstart#fetching-the-graphql-schema), it needs a copy of the schema in a file
- I found [`reqwest-graphql`](https://docs.rs/reqwest-graphql/latest/reqwest_graphql/#basic-usage) which doesn't need the schema in a file
  - it uses queries in raw strings, which is similar to what is currently being done
  - though it does allow for the use of stuff like `$` in the raw string
  - and unfortunately, this crate doesn't look well-maintained

I'm leaning towards keeping the query building as-is and not using a client, let me know what you think.

2025-01-07 14:28 UTC, garryod commented on graph-proxy/src/graphql/workflows.rs
> +        );
Yeah, none of those look like terrific options, a `format!` string seems like the call

2025-01-08 14:37 UTC, yousefmoazzam commented on graph-proxy/src/graphql/workflows.rs
> +        });
No worries; if the objects had multiple fields then maybe `map` would be worth it, but I agree for this case it's unnecessary, and clearer to just write the objects explicitly

2025-01-08 15:51 UTC, yousefmoazzam commented
Finally got it working with `mockito`, I think I prefer it for two reasons (in addition to being better maintained as pointed out by @iamvigneshwars):
- it caught an issue which wasn't caught by `httpmock` (which is why I added another test in ee31e69)
- the order of the definition of the two mock endpoints in the pagination test doesn't matter with `mockito`, but it did matter with `httpmock` (one ordering failed, the other passed)

2025-01-09 10:40 UTC, yousefmoazzam commented on .github/workflows/_graph_proxy_code.yaml
> +          --release
Ok, I used a `.cargo/config.toml` file to specify the `RUST_MIN_STACK` env var. [Docs](https://doc.rust-lang.org/cargo/reference/config.html#configuration-format) say this will be present for any process that `cargo` runs, so this also gets rid of the stack overflow when running `cargo run serve`.

I'm not familiar with this `.cargo/config.toml` file though, so let me know if this isn't quite the right config.

(The other thing I found in rust docs for setting env vars was [build script stuff](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-env), though they explicitly say this should only be used for env var inspection at compile-time using `env!`).

2025-01-09 10:50 UTC, garryod commented on graph-proxy/.cargo/config.toml
> +RUST_MIN_STACK = "4194304"
Would be nice to have a human readable size here

```suggestion
RUST_MIN_STACK = "4194304" # 4MiB
```

2025-01-09 10:51 UTC, garryod commented on graph-proxy/src/graphql/workflows.rs
> +    use crate::graphql::root_schema_builder;
Nit: would rather if these weren't separated, and we didn't use the wildcard import on `super`

2025-01-09 10:58 UTC, garryod commented on graph-proxy/src/graphql/workflows.rs
> +        let namespace = format!("{}{}-{}", proposal_code, proposal_number, number);
We should probably use `crate::graphql::Visit` here. The `to_string` of which would produce your `namespace`

2025-01-09 11:43 UTC, yousefmoazzam commented on graph-proxy/src/graphql/workflows.rs
> +    use crate::graphql::root_schema_builder;
Nice, I didn't know `rustfmt` ordered imports for you if there's no newlines between them

2025-01-09 13:53 UTC, garryod approved these changes
LGTM

2025-01-09 14:17 UTC, merged