Monitoring Stack setup
DiamondLightSource/workflows pull request #324
Opened 2024-12-10 10:49 UTC by iamvigneshwars

2025-01-06 14:23 UTC, garryod requested changes
Looking good, any chance of a standalone app so we can deploy this with the argus ArgoCD?

2025-01-16 11:14 UTC, iamvigneshwars commented on charts/monitoring/values.yaml
> +      secretName: letsencrypt-grafana-workflows-diamond-ac-uk
Think we should just include it as a sealed secret

2025-01-28 11:03 UTC, garryod requested changes

2025-01-28 11:03 UTC, garryod commented on charts/monitoring/values.yaml
> +      enabled: false
Do we need these if it's disabled?

2025-01-28 11:03 UTC, garryod commented on charts/monitoring/values.yaml
> +      name: default-full-access-mounted
Can we avoid using `default-full-access-mounted`? Looks like we might need to create our own `Role` & `RoleBinding` here

2025-01-28 14:04 UTC, iamvigneshwars commented on charts/monitoring/values.yaml
> +        url: "http://{{ .Release.Name }}-thanos-query-frontend:9090"
I think `.Release.Name` would be more accurate here

2025-01-28 14:28 UTC, iamvigneshwars commented on charts/monitoring/values.yaml
> +      enabled: false
By default it's enabled

2025-01-28 14:44 UTC, iamvigneshwars commented on charts/monitoring/values.yaml
> +      name: default-full-access-mounted
seems to work fine without creating `Role` & `RoleBinding`

2025-01-28 14:44 UTC, iamvigneshwars commented on charts/monitoring/values.yaml
> +    create: false
Yeah, but we don't want grafana to create any other roles!

2025-01-28 15:11 UTC, garryod requested changes

2025-01-28 15:11 UTC, garryod commented on charts/monitoring/templates/otel-collector-rolebinding.yaml
> +    namespace: workflows
This should be templated

2025-01-28 15:11 UTC, garryod commented on charts/monitoring/templates/otel-collector-rolebinding.yaml
> +    name: "{{ .Release.Name }}-opentelemetry-collector"
Can we stick with either `otel-collector` or `opentelemetry-collector` throughout?

2025-01-28 15:11 UTC, garryod commented on charts/monitoring/values.yaml
> +      enabled: false
Ah, my bad, I misread the `queryFrontend.ingress.enabled` as simply `queryFrontend.enabled`

2025-01-29 10:58 UTC, merged